# Generated by Django 5.1.3 on 2024-12-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='stud_status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
